In [57]:
# 下载数据集
# wget https://raw.githubusercontent.com/wenyuange/dao/master/%E8%97%8F%E5%A4%96/%E5%BA%84%E5%AD%90.txt
with open("悟真篇.txt", "r", encoding="utf-8") as f:
    text = f.read()

print(text[:1000])

悟真篇

　　　
　序
　　嗟夫！人身难得，光阴易迁，罔测修短，安逃业报？不自及早省悟，惟只甘分待终，若临歧一念有差，立堕三涂恶趣，则动经尘劫，无有出期。当此之时，虽悔何及？故老释以性命学开方便之门，教人修种，以逃生死。释氏以空寂为宗，若顿悟圆通，则直超彼岸；如有习漏未尽，则尚徇于有生。老氏以炼养为真，若得其枢要，则立跻圣位；如其未明本性，则犹滞于幻形。

　　其次，《周易》有穷理尽性至命之辞，鲁语有毋意必固我之说，此又仲尼极臻乎性命之奥也。然其言之常略，而不至于详者，何也？盖欲序正人伦，施仁义礼乐有为之教。故于无为之道，未尝显言。但以命术寓诸《易》象，以性法混诸微言耳。至于《庄子》推穷物累逍遥之性，《孟子》善养浩然之气，皆切几之矣。

　　迨夫汉魏伯阳引《易》道阴阳交姤之体，作《参同契》以明大丹之作用，唐忠国师于语录首叙老庄言，以显至道之本末，如此岂非教虽分三，道乃归一。奈何后世黄缁之流，各自专门，互相非是，致使三家旨要迷没邪歧，不能混而同归矣！且今人以道门尚于修命，而不知修命之法，理出两端，有易遇而难成者，有难遇而易成者。如炼五芽之气，服七耀之光，注想按摩，纳清吐浊，念经持咒，噀水叱符，叩齿集神，休妻绝粒，存神闭息，运眉间之思，补脑还精，习房中之术，以致服炼金石草木之类，皆易遇难成者。已上诸法，于修身之道，率皆灭裂，故施功虽多，而求效莫验。若勤心苦志，日夕修持，止可避病，免其非横。一旦不行，则前功渐弃。此乃迁延岁月，必难成功。欲望一得永得，还婴返老，变化飞升，不亦难乎？深可痛伤！盖近世修行之徒，妄有执着，不悟妙法之真，却怨神仙谩语。殊不知成道者，皆因炼金丹而得。恐泄天机，遂托名数事而名。其中惟闭息一法，如能忘机息虑，即与二乘坐禅相同。若勤而行之，可以入定出神。奈何精神属阴，宅舍难固，不免常用迁徒之法。既未得金汞返还之道，又岂能回骨换阳，白日而升天哉？

　　夫炼金液还丹者，则难遇易成，须要洞晓阴阳，深达造化，方能追二气于黄道，会三性于元宫，攒簇五行，和合四象，龙吟虎啸，夫唱妇随，玉鼎汤煎，金炉火炽，始得玄珠成象，太乙归真。都来片饷工夫，永保无穷逸乐。至若防危虑险，慎于运用抽添，养正持盈，要在守雌抱一。自然返阳生之气，剥阴杀之形。节气既周，脱胎神化，名题仙籍，位号真人，此乃大丈夫功成名遂之时也。今之学者，有取铅汞为二气，指脏腑为五行，分心肾为坎离，以肝肺为龙虎，用

In [58]:
# 获取词表及其大小
chars = sorted(list(set(text)))
vocab_size = len(chars)
print("".join(chars))
print(f"vocab_size: {vocab_size}")


“”　、。《》一丁七万丈三上下不与丑专且世业东两严丧个中丰临丹为主举乃义之乌乍乎乐乖乘乙九也习乡书买乱乾了争事二于亏云互五井亡亢交亦产亭亲人亿仁仆今仍从仑仔他仙令以仪仰仲价任伊伏休众会传伤伦伪伯似但位低住体何余佛作你使侍依侮侯侵便俗保信修俱倏倒倘候倚倡值倾偃假偏停健傀儡儿兀元兄充兆先光克免兑兔兕入全八公六兮共关兴兵其典兹养兼兽内再军冤冥冬决冶净准减凑几凡凤凭凶出击刀刃分切刑刘则刚初利别到制刹前剑剥力劝功加劣动助劫劳势勤勾包化北匪区医十千升午半华卑卒单南卜卢卦卧卫危即却卵卷历厌厚原厮去参又及双反发叔取受变叙口古句叩只叮可台叱右叶号叹吃各合吉同名后吐向君吝吞吟否含听吹吼吾周味呼命和咎咏咒咛咽哀品哄哉响哑哮唇唐唤唱啸善喜喧嗟嘘噀噤器嚣四回因园困固国图圆土圣在圭地场均坎坐坠坤坦垂垢城基堂堆堕堪塞境增壅士壬壮声壶处备复夏夕外夙多夜大天太夫夭央失头夷夸夺奇奈奋契奔奥女好如妄妇妖妙妥妨妻妾始姑姓委姤姹姻威娉娟娥婆婴媒嫁子孔孕字存孙孟孤学宁宅守安宗官定宜宝实审客室宫害宵家容宾寂寄寅富寒寓寝察寸对寻导寿封射将尊小少尔尘尚尝尪就尸尼尽尾居屋属屡履屯山岁岂岳岸峰崇川巢工左巧巨差己已市布师希帷常幌平年并幻幼幽庄序应底庚度庭庶廓廛延开异弃弄引张弥弦弹强归当录形影役彻彼往待徇律徒得循微德心必忆忌忍志忘忙忠忧念忽怀怎怕思急性怨怪总恁恋恍恐恒恣恩恪息恰恶恼悉悔悟患悦悲悴情惊惑惚惜惟惧想愆愈意愚感愿慈慎慧慨慷憔戊戌成我戒或战户房所手才打托执扶把抑投抛报披抱抽担拒拘招拟拣拨择拯持指按捉捐损换据授掌接推掾揆提握揣搏搦携摄摆摘摩撰撼擒攒收攸改攻放故效敌敏救教敢散数敲文斗斟斤斩断斯新方於施旁旅旋无既日旦旧旨早旬时旺昆昌明昏易昔映昧昨昭是昼显晓晦晨普景智暂暑暗曜曰曲更曾最月有服朔朗望朝期木未末本术朱朴机朽杀杂权杖来杳极枉林果枝枢枣枯染柔柴栖校样根栽桎桑桥梏梦梯森棺椎榜榭樊模横檬次欢欧欲欺款歌止正此步歧死殊毁毂毋母每比毕毗毛毫氏民气氤氲水永求汉汝汞江池汤沉沐沙没沦河沸泄泉泊法泡波泥注泰洞津洼派流浅浆浊测济浑浩浪浮浴海浸涂消涉涧液深淳混添清渐渡温渴游湛湿溉源溪溺滓滞满漂漏演漕漫潜潭澄灌火灭灯灵灶灾炁炉炭点炼炽烁烈烛烦烧热烹焉焚焰然煅煎煞照煮熏熙熟熬爱爻片牛牝牢物牵特状犹狂独狮狱猖猛猜猿玄率玉王玩现珍珠理琴瑞瑶甘甚生用田由甲申电男畅界畏留略疏疗病痕痛痴癸白百的皆皇皎盈益盖盗盛目直相省眉看真眠眼着睡睹矣知短石砂研破

In [59]:
# 建立编码器和解码器
stoi = {c:i for i,c in enumerate(chars)}
itos = {i:c for i,c in enumerate(chars)}
encode = lambda s : [stoi[c] for c in s]
decode = lambda l : "".join([itos[i] for i in l])

print(encode("道可道，非常道"))
print(decode(encode("道可道，非常道")))

[1343, 262, 1343, 1511, 1441, 493, 1343]
道可道，非常道


In [60]:
# 构建编码数据
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])

torch.Size([13093]) torch.int64
tensor([ 574,  987, 1056,    0,    0,    3,    3,    3,    0,    3,  502,    0,
           3,    3,  313,  369, 1508,   70, 1289, 1425,  535, 1511,  143, 1409,
         703, 1307, 1511, 1094,  843,  119,  995, 1511,  421, 1325,   22,  619,
        1514,   16, 1133,  247,  695,  984,  574, 1511,  584,  260,  948,  186,
         531, 1080, 1511, 1153,   30,  792,    8,  549,  728,  485, 1511, 1035,
         346,   13,  852,  570, 1278, 1511,  190,  206, 1081,  457,  208, 1511,
         689,  728,  182,  734,    5,  523,  790,   37,  697, 1511, 1179,  573,
         104,  247, 1514,  665, 1107, 1367,   82,  556,  291,  417,  512,  683,
         115,   37, 1393, 1511])


In [61]:
# 分开训练集和验证集
n = int(0.9 * len(text))
train_data = data[:n]
val_data = data[n:]

In [62]:
# 上下文长度
block_size = 8
print(train_data[:block_size+1])

# 数据和标签的示例
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when context is {context}, target is {target}")

tensor([ 574,  987, 1056,    0,    0,    3,    3,    3,    0])
when context is tensor([574]), target is 987
when context is tensor([574, 987]), target is 1056
when context is tensor([ 574,  987, 1056]), target is 0
when context is tensor([ 574,  987, 1056,    0]), target is 0
when context is tensor([ 574,  987, 1056,    0,    0]), target is 3
when context is tensor([ 574,  987, 1056,    0,    0,    3]), target is 3
when context is tensor([ 574,  987, 1056,    0,    0,    3,    3]), target is 3
when context is tensor([ 574,  987, 1056,    0,    0,    3,    3,    3]), target is 0


In [63]:
# 获取批次维度的数据
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch("train")
print("inputs:")
print(xb.shape)
print(xb)
print("targets:")
print(yb.shape)
print(yb)

for b in range(batch_size):
    print(f"Batch {b}:")
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"when context is {context}, target is {target}")


inputs:
torch.Size([4, 8])
tensor([[   3,    3, 1372, 1501,  784,  961,  740, 1368],
        [   0,    3,    3, 1241,    6,  288,  703,  245],
        [1387, 1511, 1014,  335,  957,  383, 1511, 1123],
        [ 964, 1511,  965,  485, 1160,  724,  104,  685]])
targets:
torch.Size([4, 8])
tensor([[   3, 1372, 1501,  784,  961,  740, 1368,  815],
        [   3,    3, 1241,    6,  288,  703,  245,  273],
        [1511, 1014,  335,  957,  383, 1511, 1123,  601],
        [1511,  965,  485, 1160,  724,  104,  685,    5]])
Batch 0:
when context is tensor([3]), target is 3
when context is tensor([3, 3]), target is 1372
when context is tensor([   3,    3, 1372]), target is 1501
when context is tensor([   3,    3, 1372, 1501]), target is 784
when context is tensor([   3,    3, 1372, 1501,  784]), target is 961
when context is tensor([   3,    3, 1372, 1501,  784,  961]), target is 740
when context is tensor([   3,    3, 1372, 1501,  784,  961,  740]), target is 1368
when context is tensor([   3, 

In [64]:
import torch
import torch.nn as nn
from torch.nn import functional as F


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device: {device}")
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()

        self.token_embeding_table = nn.Embedding(vocab_size, vocab_size, device=device)

    def forward(self, idx, targets=None):
        logits = self.token_embeding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, _ = self(idx)
            logits = logits[:, -1, :] # focus on last time step
            probs = F.softmax(logits, dim=-1) # B, C
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx
    

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb.to(device), yb.to(device))
print(logits.shape)
print(loss)

m.to("cpu")
idx = torch.zeros((1,1), dtype=torch.long)
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))

device: cuda
torch.Size([32, 1515])
tensor(7.8161, device='cuda:0', grad_fn=<NllLossBackward0>)

法熙籍灶认盈通慨冶冬乾烈吹粗始戌岳威脏鉴恐祸咽依住工椎求冬施细略立逝补梦恍游浆路温唐故休霞非欧谴怕根见浴卵蛇兵毋志你绵妙奥反掌蛇切性坠骸打先子祯惧爻涂端倒隔着牢算丧般根觉射夜本晨辉着种水省疗炉姻笼买悔


In [65]:
# 创建优化器
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [66]:
# 训练
batch_size = 128
m = m.to(device)
for step in range(1000):
    xb, yb = get_batch("train")
    logits, loss = m(xb.to(device), yb.to(device))
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.to("cpu").item())

6.705099582672119


In [67]:
# 测试
print(decode(m.generate(torch.zeros((1,1), dtype=torch.long).to(device), max_new_tokens=500).to("cpu")[0].tolist()))


所倏哑担丧派造倾兆再贤绿界煮朗每秋牝真敲深浆尼预忽辞腹妾曾暗定火胎亏居算逸欲隐预五休绵校仪赞孙役悟河惜才称齐忧悉柔器北；知热恼限镬薄桑骸夙兹忌灯恰徒舟争熏骞咛遗含差从稚慈赤宁野和鉴国晦被逢寻达弄芝惚冥幻慨空故容周纵珠瑶疗火抽炁补脑柴厚成泰夫英短黄遗位戒弥忠跻卑换定骸陀俱善离丑坠谴财噤乾携玉卦尘注寅风沸刃侵午寒枢镜派蛟载款井差独玩恋扶刚籁笼妄栖仑郁稳骸滓和仑幼宾梯夙杳次秘篇菲叱了山别湿三
高信救宝封卧妄右拣散口侍离个卫希引拣临闻蹄巧使憔碍说嫁源继善丑偃莹肾踵取遥造边玉猿委丑
各如纳妄庄缠七顾咛渡眠饮汤夙助海蟾苦侮三闹答日吹扶噤悴采
垂披漕红源弹霞爻期冬冶腑好驻雨愿霎念孟导随睡以时含头溺私省跻更且从西缰被孟竹焚别剑止陇绿敲蛇讽更图叶牛般健宁般堆烛清危城蒙累浊纤骑余晓居再榭诀佛念。眠哄延产进会转亦寻癸谋盗六头取胜拘迫旧潜要莲劣位芸举丹被彻停总项冬向辐志就森闾吞律？秋白氏麟寂炉蹄丰服塞饷渡觅茅左吉罪比瑶鹊熬驻铸换尝珍兹家通并旨呼色载卢逃烧缠咎病住台响高韵寿逍助捉冬持室姑揣旋肯吐远鹊衣幌秘蹄簇沸担吞怨厮穷涂车过巢证永注桑片访痴倒尽丑健引磊旧碓摄烈麟应竺磊婴霎术题侵兵衣唤祯但饭言市芝凤躐禁兴集姻漏
